custom_components/myskoda/__init__.py
custom_components/myskoda/binary_sensor.py
custom_components/myskoda/climate.py
custom_components/myskoda/config_flow.py
custom_components/myskoda/device_tracker.py
custom_components/myskoda/entity.py
custom_components/myskoda/number.py
custom_components/myskoda/sensor.py
custom_components/myskoda/switch.py

Incomplete. Put up to for discussion purposes.

WIP: align with current models in myskoda

---

README.md
custom_components/myskoda/__init__.py
custom_components/myskoda/number.py

Nothing major going on, just trying to point out this is not just for Enyaq :-)

(chore) Small textual update since were targetting more than Enyaq

---

custom_components/myskoda/translations/en.json
poetry.lock

Translates basic config flow
Needs #6 so we can lint it from the start

Translate config flow

---

custom_components/myskoda/switch.py
poetry.lock

Charge Care was using incorrect type, causing the switch state to always be in "off" position.

Fix Charge Care state

---

custom_components/myskoda/binary_sensor.py

Implement sunroof

---

.pre-commit-config.yaml

Just a basic pre-commit setup to extend upon

Add precommit

---

custom_components/myskoda/config_flow.py
custom_components/myskoda/manifest.json
poetry.lock
pyproject.toml

Fixes https://github.com/skodaconnect/homeassistant-myskoda/issues/31
Going to just merge this to unblock users but feel free to leave comments anyway

Fix configflow myskoda

---

custom_components/myskoda/__init__.py
custom_components/myskoda/coordinator.py
custom_components/myskoda/translations/en.json

Stop using HA default referrals. Apparently they don't work for custom integrations
Fixes #30

Fix EN tranlations

---

custom_components/myskoda/__init__.py
custom_components/myskoda/binary_sensor.py

According to https://www.home-assistant.io/integrations/binary_sensor/#device-class it's inverse from what you'd expect..
Fixes #37

Fix door lockstate

---

hacs.json
poetry.lock
pyproject.toml

Set minimal HA version to 2024.10.0b0

---

custom_components/myskoda/manifest.json
poetry.lock
pyproject.toml

- Bump library
- Set our own version number

Release v1.5.0

---

custom_components/myskoda/sensor.py

Fix error when ChargingStatus.State is absent/None

---

custom_components/myskoda/binary_sensor.py
poetry.lock
pyproject.toml

Fixes #84 
Will be released after 1.4.6 (needs lib update)

Set lock to unavailable when status is INVALID

---

custom_components/myskoda/coordinator.py

Improve handling of failed MQTT operation

---

custom_components/myskoda/coordinator.py

- Adds detection of regular polls failing and raises `UpdateFailed` to let HA handle this
- Adds detection of update requests following MQTT updates failing and lets HA handle this as well

Improve robustness of processing updates from MySkoda

---

custom_components/myskoda/climate.py

Fix being unable to turn on HVAC from webinterface

---

custom_components/myskoda/manifest.json
poetry.lock
pyproject.toml

Bump version to `1.6.3`
Bump dependencies to `myskoda==0.8.5`

Prepare for release of 1.6.3

---

custom_components/myskoda/binary_sensor.py
custom_components/myskoda/climate.py
custom_components/myskoda/image.py
custom_components/myskoda/number.py
custom_components/myskoda/sensor.py
custom_components/myskoda/translations/en.json

- Remove name from entities since this disables translation of entity names
- Add translatable states for binary sensors

Small translation updates

---

custom_components/myskoda/sensor.py
custom_components/myskoda/translations/en.json

Activate InspectionInterval Sensor
Add translation for the sensor
Sort translations file alphabetically for easier lookup when adding translations
All `DURATION` type sensors currently suffer from a frontend bug, causing days to be rendered as hours
https://github.com/home-assistant/frontend/issues/18151
Related to #165

Activate Inspection Interval

---

custom_components/myskoda/sensor.py
custom_components/myskoda/translations/en.json

Add Charging Rate sensor

---

custom_components/myskoda/translations/ru.json

Translation to Russian Language

Russian translation

---

custom_components/myskoda/manifest.json
poetry.lock
pyproject.toml

Set version to 1.8.0
Set library to 0.9.1

Prepare release 1.8.0

---

custom_components/myskoda/coordinator.py
custom_components/myskoda/manifest.json
pyproject.toml

Also prepare release 1.8.1
Fixes #215

Correct polling interval to actually use minutes, not seconds

---

custom_components/myskoda/coordinator.py
custom_components/myskoda/manifest.json
custom_components/myskoda/sensor.py
poetry.lock
pyproject.toml

* Depend on myskoda 0.10.0
* Set version to 1.8.2

Prepare v1.8.2

---

custom_components/myskoda/icons.json
custom_components/myskoda/sensor.py
custom_components/myskoda/translations/en.json

Add 3 new sensors, for ICE cars only
- Inspection Interval in Kilometers
- Oil Service Interval in Days
- Oil Service Interval in Kilometers
Fixes #242

Oil Inspection Sensor

---

custom_components/myskoda/translations/de.json

Changed "lights_on" to "parkinglights_on"

Update de.json "parkinglights_on"

---

custom_components/myskoda/entity.py
custom_components/myskoda/image.py

Fixes #282 
Awaiting feedback from requestor to see if this is what's needed

Add available vehicle and composite image URLs

---

.github/workflows/stale.yml

Essentially a copy of `homeassistant-skodaconnect`

Add stale issue bot

---

custom_components/myskoda/manifest.json
pyproject.toml

Prepare release 1.9.1

---

.github/workflows/stale.yml
custom_components/myskoda/__init__.py
custom_components/myskoda/issues.py
custom_components/myskoda/translations/en.json

Add issue creator for new terms and conditions from myskoda

Improve user notifications for new Terms and Conditions

---

custom_components/myskoda/manifest.json
poetry.lock
pyproject.toml

In succession of #312 
- Bump myskoda library to 0.12.2

Prepare release 1.10.0

---

custom_components/myskoda/sensor.py

Due to missing subscriptions for the STATE capability the driving_range can be missing while the battery data is available.
Fixes #302

Let Range fall back to battery if driving_range is missing

---

README.md

Add disclaimer in README

---

README.md

Fix 404 links on HACS website.

Update README.md to fix 404 links to hacs.xyz

---

custom_components/myskoda/climate.py
custom_components/myskoda/manifest.json
poetry.lock
pyproject.toml

- Bump myskoda to v0.13.0
- Fix incompatibilities in `start_auxiliary_heater` call in `myskoda-0.13.0`

Prepare release 1.11.0

---

custom_components/myskoda/manifest.json
pyproject.toml

Prepare release 1.11.1

---

custom_components/myskoda/manifest.json
poetry.lock
pyproject.toml

* Bump library to 0.13.2
* Allow python 3.13 for dev build compatibility

Prepare release 1.12.0

---

custom_components/myskoda/manifest.json
custom_components/myskoda/sensor.py
poetry.lock
pyproject.toml

Bump myskoda to 0.13.3
Fix places where soc may be used while it was `None` due to the new default

Prepare release 1.12.1

---

custom_components/myskoda/manifest.json
pyproject.toml

Prepare version 1.13.1

---

custom_components/myskoda/icons.json
custom_components/myskoda/sensor.py
custom_components/myskoda/translations/en.json

Add Outside temperature sensor entity

---

custom_components/myskoda/manifest.json
pyproject.toml

Prepare release 1.14.0

---

custom_components/myskoda/manifest.json
pyproject.toml

Bugfix release 1.14.1

---

custom_components/myskoda/manifest.json
pyproject.toml

Prepare release 1.14.2

---

README.md

- Add a link to the version shield so it navigates to the releases page
- Add link to crowdin to the localization badge

Add links to shields

---

custom_components/myskoda/coordinator.py

Fix NoneType when trying to detect model that has not been polled yet

Fix NoneType in initial startup

---

.github/workflows/release.yml

Revert #460 because it breaks our release flow

Revert releaser

---

custom_components/myskoda/quality_scale.yaml

This adds a todo-list for the new HA quality scale

Add quality scale

---

README.md

Document adding a vehicle

---

custom_components/myskoda/diagnostics.py

this will add possibility to generate diagnostics directly from the integration section for all available vehicles. Format and structure is same as for device diagnostics.

add generate diagnostics feature for the config entry section

---

README.md
custom_components/myskoda/coordinator.py
custom_components/myskoda/icons.json
custom_components/myskoda/switch.py
custom_components/myskoda/translations/en.json

This will add a switch for all 3 departure timers. Additionally whole timer configuration is stored in custom attributes

Add Departure Timer 1,2,3 switch

---

custom_components/myskoda/translations/ro.json

Thanks for the great integration! Please find attached the romanian translation.
Enjoy!
Bogdan

Added romanian translation

---

custom_components/myskoda/sensor.py

Remove battery deviceclass from TargetBatteryPercentage

---

custom_components/myskoda/manifest.json
poetry.lock
pyproject.toml

- Adds airconditioning timers
- Avoids getting health info if this would wake up the car
- Dependency updates

Bump myskoda to 0.17.0

---

custom_components/myskoda/config_flow.py

Handle ClientResponseError during integration config flow

---

.github/release.yml

The "others" category was getting a bit busy.

Update categories for changelog generator

---

custom_components/myskoda/manifest.json
pyproject.toml

Prepare release of 1.19.0

---

custom_components/myskoda/__init__.py

- Notify HA of migration success
- Add robustness in code
Fixes #570

Fix bug in migration causing a KeyError upon initialisation

---

custom_components/myskoda/translations/cs.json
custom_components/myskoda/translations/sk.json

Even I'm using HA in english , noticed some czech and slovak translation are totally incorrect and decided to fix it.
Especially the part with AC for air-conditioning is translated as alternating current which is missleading

Fix slovak and czech translation

---

.github/workflows/release.yml

This reverts commit 04f1c214bacd07bf59b9a0622e8b3f1ea8490899.

Revert "Fix another releaser typo (#591)"

---

.github/workflows/release.yml

Reverts skodaconnect/homeassistant-myskoda#590

Revert "Fix typo in releaser"

---

custom_components/myskoda/config_flow.py
custom_components/myskoda/translations/en.json

- Improve config flow error translatables
- Add detection for Terms and Conditions and Marketing updates
This improves user experience when MySkoda is having issues, or if you need to relogin for profile updates

Improve config flow error

---

custom_components/myskoda/manifest.json
pyproject.toml

Prepare release v1.20.0

---

custom_components/myskoda/manifest.json
hacs.json
poetry.lock
pyproject.toml

- Bump myskoda to 0.21.0
- Rework python requirement
- Set new version to 1.21.0

Prepare new release

---

custom_components/myskoda/manifest.json
poetry.lock
pyproject.toml

Release v1.21.1 with myskoda==0.21.1

---

custom_components/myskoda/__init__.py
custom_components/myskoda/binary_sensor.py
custom_components/myskoda/button.py
custom_components/myskoda/climate.py
custom_components/myskoda/config_flow.py
custom_components/myskoda/coordinator.py
custom_components/myskoda/device_tracker.py
custom_components/myskoda/diagnostics.py
custom_components/myskoda/error_handlers.py
custom_components/myskoda/image.py
custom_components/myskoda/lock.py
custom_components/myskoda/number.py
custom_components/myskoda/sensor.py
custom_components/myskoda/switch.py

Improve typing by proving a bound ConfigEntry called MySkodaConfigEntry
Preparing for [strict typing](https://developers.home-assistant.io/docs/core/integration-quality-scale/rules/strict-typing)

Improve typing: ConfigEntry -> MySkodaConfigEntry

---

custom_components/myskoda/manifest.json
pyproject.toml

Prepare for bugfix/documentation update release

Set version to 1.21.2

---

custom_components/myskoda/error_handlers.py

During testing of the new release, a circular import issue was found. This is a hotfix to allow releasing. A new issue will be created to permanently fix this.

Hotfix for circular imports

---

custom_components/myskoda/manifest.json
pyproject.toml

Do a proper release, we didn't update the version in 1.21.5

Set version to 1.21.5

---

README.md

Add section on push/pull strategy. Fixes #700 
Add section to HACS install on reboot of HA. Fixes #696

Documentation updates for push/pull and HACS install

---

.github/release.yml

Adds regression label and implements use of documentation in a seperate header.

Adjust categories of releaser

---

custom_components/myskoda/manifest.json
poetry.lock
pyproject.toml

✨ New features
- Add brand configuration for future support of multiple brands
- Initial implementation of charging profiles
🐛 Bugfixes
- Add capability ACCIDENT_DAMAGE_MANAGEMENT

Bump myskoda to 0.22.0

---

custom_components/myskoda/manifest.json
poetry.lock
pyproject.toml

This adds an "unknown" enginetype to help fix #710

Bump myskoda to 0.22.1

---

custom_components/myskoda/manifest.json
pyproject.toml

Set version to 1.22.0

---

custom_components/myskoda/__init__.py

Small cleanup. This bothered me reading through the code.
Also, add proper unloading of the MQTT open connection upon unload.

Replace config field names with their constants

---

custom_components/myskoda/icons.json
custom_components/myskoda/sensor.py
custom_components/myskoda/translations/en.json

Similar to the time left for AC, but this time for vehicles equipped with an auxiliary heater
TODO: Add translations

Add time left sensor for auxiliary heater

---

custom_components/myskoda/lock.py
custom_components/myskoda/translations/en.json

Tell user S-PIN is missing when operating a lock

---

custom_components/myskoda/__init__.py
custom_components/myskoda/translations/en.json

Improve terms-and-conditions login error

---

custom_components/myskoda/sensor.py

Fixes #766 (maybe)
The Skoda API sometimes returns an incorrect (old) mileage. This workaround inspects the last recorded value, if there is one, and uses that if it happens to be larged than the value returned by the API.
To test I added a logline for `last_value` and it seems to get the expected value
```
2025-04-30T19:04:32.111307325Z 2025-04-30 19:04:32.102 INFO (MainThread) [custom_components.myskoda.sensor] XXXX LAST_VALUE = 54606
```

feat: work around API sending incorrect mileage

---

README.md
docs/design.md
docs/entities.md

I initially just planned to add an FAQ so we have a place to document recurring questions/issues, but I ended up reworking the whole README quite a bit.
Goals:
- Make it shorter and simpler. Moved out a few things to separate files in a docs directory
- Put the most important info at the top

doc: update README, add FAQ

---

.github/workflows/crowdin-download.yml

Make crowdin PR's follow conventional-commits. 
Add language details to PR/commit

chore(i10n): improve crowdin's PR style

---

.github/workflows/crowdin-download.yml

Language list doesn't work. Removing it and will add a working version later on.

chore(i10n): remove language list from crowdin pr

---

custom_components/myskoda/manifest.json
pyproject.toml
uv.lock

https://github.com/skodaconnect/myskoda/releases/tag/v1.2.2

chore(deps): bump myskoda to 1.2.2

---

custom_components/myskoda/manifest.json
pyproject.toml
uv.lock

https://github.com/skodaconnect/myskoda/releases/tag/v1.2.3

chore(deps): bump myskoda to v1.2.3

---

custom_components/myskoda/manifest.json

Set version to 1.25.0 in preparation of a new release

chore: bump version to 1.25.0

---

custom_components/myskoda/sensor.py

fix: actually initialize the GasRange entity

---

custom_components/myskoda/manifest.json

Small bugfix release for the CNG mileage sensor

chore: bump version to 1.25.2

---

custom_components/myskoda/manifest.json
pyproject.toml
uv.lock

Fixes another issue in serialization of `Booking`
Fixes #841

chore: bump myskoda to 2.2.2, bump version to 1.28.3

---

custom_components/myskoda/lock.py

After #750 and #880 this fixes the lock entity
I think this is the last entity type that writes to the car
Fixes #754

Refactor lock changing and logging

---

custom_components/myskoda/sensor.py

Show correct value when battery% is 0

---

custom_components/myskoda/device_tracker.py

Additional fix for https://github.com/skodaconnect/homeassistant-myskoda/issues/913

Apply state_of_charge fix to device tracker as well
