skodaconnect/homeassistant-myskoda

- custom_components/myskoda/entity.py
- poetry.lock
VIN is missing for end-users, this exposes it as the serial number for the car.
> Add VIN to device info

- custom_components/myskoda/device_tracker.py
When a car does not transmit it's coordinates, or has coordinates turned off, this causes an error in the current integration. Should be fixed with this update.
> Fix unavailable device tracker

- custom_components/myskoda/sensor.py
- custom_components/myskoda/switch.py
- custom_components/myskoda/translations/en.json
- Add translation features to switches
- Provide more default translations in English
Fixes #56
> Expose more to translations

- README.md
- custom_components/myskoda/device_tracker.py
- poetry.lock
- pyproject.toml
- (chore) Change library dependency
- (chore) Minor cleanup
> Release 1.4.3

- .devcontainer.json
- .gitattributes
- .github/dependabot.yml
- .github/workflows/release.yml
- .github/workflows/validate.yaml
- .gitignore
- .vscode/tasks.json
- config/configuration.yaml
- poetry.lock
- pyproject.toml
- scripts/develop
- scripts/lint
- scripts/setup
This repo is commonly used as a template repo for HACS integrations.
This PR adds from there:
- VSCode devcontainer setup
- Dependabot setup
- Automatic creation of zip archive on release
- Some tweaks to current CI (limits runs to only main branch)
> Add various suggestions from ludeeus/integration_blueprint

- custom_components/myskoda/coordinator.py
The API reports in meters while MQTT charging events report in km.
Makes me wonder how this will work for cars/profiles set in imperial units...
Fixes #77
> Fix km to m conversion for mqtt charged_range

- custom_components/myskoda/device_tracker.py
- custom_components/myskoda/entity.py
- custom_components/myskoda/sensor.py
> Add image render sensor and in device tracker

- .github/workflows/crowdin-download.yml
- .github/workflows/crowdin-upload.yml
- .github/workflows/release.yml
Some workflows do not need to run on forks, since they either hold credentials, or do tasks that are not suited for forks.
> Limit workflows so they dont run on forks

- README.md
- custom_components/myskoda/climate.py
- custom_components/myskoda/device_tracker.py
- custom_components/myskoda/number.py
- custom_components/myskoda/switch.py
Currently, every climate change, including a slider from the UI, results in a request to the car.
Given that the car has limited capabilities to handle many requests, we should limit those.
This introduces a HA mechanism called 'Throttle'. Basically, this means all requests after the first one are ignored for a timeperiod. Introducing this with 30s timeperiod.
> Add throttle to prevent API credit exhaustion

- custom_components/myskoda/binary_sensor.py
- custom_components/myskoda/climate.py
- custom_components/myskoda/device_tracker.py
- custom_components/myskoda/number.py
- custom_components/myskoda/sensor.py
- custom_components/myskoda/switch.py
- custom_components/myskoda/utils.py
Instead of raising an uncaught exception in the entities when the underlying attributes in the MySkoda Vehicle object are (temporarily) missing (None), just return None. HA will show the entities as Unknown.
Fixes #49
Discord discussion: https://discord.com/channels/877164727636230184/1087487796731707402/1295108867755081800
Still need to test this but wanted to get the PR up.
> Fix InvalidCapabilityConfigurationError exceptions

- custom_components/myskoda/entity.py
This will cause entity names and IDs to include the vehicle name, making it easier to identify and use the entities, especially when having multiple vehicles. The unique_id does not change.
E.g.
```
entity_description.key = charger_connected
unique_id = TMBXXXXXXXXXXXX_charger_connected
entitiy_id = sensor.skoda_enyaq_charger_connected
name = Skoda Enyaq Charger Connected
```
Reference: https://developers.home-assistant.io/docs/core/entity/#has_entity_name-true-mandatory-for-new-integrations
Fixes #57
This will be a somewhat breaking change in that in order to benefit from the new entitiy names users will need to delete and recreate the integration.
Thanks to @joostlek for the pointer!
> Update entity names and IDs to include device name

- custom_components/myskoda/sensor.py
The translation for the Mileage sensor was not working due to a typo.
> Fix typo in Mileage sensor

- poetry.lock
- pyproject.toml
Just let HomeAssistant deal with the dependencies so we don't need to
> Removing projects we no longer directly depend on

- custom_components/myskoda/binary_sensor.py
- custom_components/myskoda/climate.py
- custom_components/myskoda/icons.json
- custom_components/myskoda/number.py
- custom_components/myskoda/sensor.py
- custom_components/myskoda/switch.py
To better align with https://developers.home-assistant.io/blog/2024/01/19/icon-translations
Also made the URL render entity a diagnostic entity, no ordinary user would need to see this on a daily basis.
> Migrate Entity icons to icons.json file

- .pre-commit-config.yaml
- custom_components/myskoda/__init__.py
- custom_components/myskoda/icons.json
- custom_components/myskoda/image.py
- custom_components/myskoda/sensor.py
- custom_components/myskoda/translations/en.json
As indicated in #129 the current display of the render image is not really nice.
This turns it from a `SensorEntity` into an actual `ImageEntity` as HomeAssistant understands it.
Additionally, this reverts #118 since it broke precommit in an environment with virtualenvs.
> Change mainrender sensor to image

- custom_components/myskoda/sensor.py
- custom_components/myskoda/translations/en.json
Currently, the value of the `charge_type` sensor is always a string, reporting "none" when no charging is happening.
This changes the behaviour to:
- Lowercase value ac/dc/off when we get a reply
- Unknown when we do not get a reply
- Adds translation for ac/dc/off
> Fix value of charge_type sensor

- custom_components/myskoda/binary_sensor.py
Sunroof was accidentally untranslated and would list as 'Opening'
> Add translation key for sunroof

- custom_components/myskoda/device_tracker.py
- custom_components/myskoda/translations/en.json
> Detect device motion

- custom_components/myskoda/entity.py
- custom_components/myskoda/utils.py
Forbidden capabilities are capabilities that cannot be present for a sensor to be added.
They are effectively the reverse of required capabilities, that must be present for a sensor to be added.
The logic added in this PR is follows:
- A sensor will be added when the vehicle has *none* of the capabilities in forbidden capabilities and *all* of the capabilities in required capabilities
Example here is the battery-care switch for a Superb iV:
The Superb iV does not have the function, but it does support the CHARGING capability.
When you add the CHARGING_MQB capability to the forbidden capabilities, the battery-care switch will now never be added for the Superb iV:
> Add forbidden capabilities

- custom_components/myskoda/number.py
- custom_components/myskoda/switch.py
> Disable ChargeLimit and BatteryCare for Superb iV

- custom_components/myskoda/sensor.py
All other fixtures show "None"
Fixes #222
> Only show software version for MEB vehicles

- custom_components/myskoda/translations/cs.json
- custom_components/myskoda/translations/da.json
- custom_components/myskoda/translations/de.json
- custom_components/myskoda/translations/en.json
- custom_components/myskoda/translations/fi.json
- custom_components/myskoda/translations/hu.json
- custom_components/myskoda/translations/it.json
- custom_components/myskoda/translations/nl.json
- custom_components/myskoda/translations/no.json
- custom_components/myskoda/translations/pt-BR.json
- custom_components/myskoda/translations/pt.json
- custom_components/myskoda/translations/ru.json
- custom_components/myskoda/translations/sv.json
Fixes #137
We may have misunderstood what Skoda and their API mean with a charging status of `CONNECT_CABLE`
We've been assuming it means "You need to connect the cable" but instead it probably means "There is a cable connected but that's it, we're neither charging nor ready to charge".
A better translation is "No Power".
Note that the binary_sensor `charger_connected` already tells us exactly if a charge cable is connected or not.
Translations based on google translate ...
> Update translations for charging state connect_cable

- custom_components/myskoda/coordinator.py
Currently HA throws an exception inside the logs when an update fails.
This makes HA handle the failure nicer
> Trigger proper exceptions inside HA when an update fails

- custom_components/myskoda/binary_sensor.py
- custom_components/myskoda/icons.json
- custom_components/myskoda/translations/en.json
Lights were incorrectly named, as in reality they represent parkinglights.
This removes the lights entity and introduces a new parkinglights entity without any functional change
Fixes #245
> Rename lights to parkinglights

- custom_components/myskoda/icons.json
- custom_components/myskoda/sensor.py
Changed range to use value from driving_range.total_range_in_km instead of a value from charging (so it can be used by all engine types)
> Change range to work with all car types, make icon car-type dependant

- custom_components/myskoda/coordinator.py
We did not process updates on remaining time to charge from MQTT.
This adds processing of this data and stores it, so related entities can update themselves.
> Improve processing of remaining time to charge

- custom_components/myskoda/__init__.py
There appears to be no event in HA that handles unloading an integration, only a `config_entry`, so we only need to keep the session alive.
Fixes skodaconnect/myskoda#185
> Fix aiohttp autocleanup

- README.md
- custom_components/myskoda/climate.py
- custom_components/myskoda/coordinator.py
- custom_components/myskoda/icons.json
- custom_components/myskoda/translations/en.json
Auxiliary heater added as separate climate entity.
When started, and AC already running, AC must be switched off first. The same is valid for AC - when started and Auxiliary heater already running, auxiliary heater must be switched off first. If not, car will not change heater source
> Added auxiliary heater climate entity

- custom_components/myskoda/climate.py
Found during testing v1.11.0 locally.
Apparently this does not work when setting flags upon initialisation, gives following errors and renders AC entity functionally broken:
```024-11-26 11:24:41.766 INFO (MainThread) [homeassistant.components.climate] Setting up myskoda.climate
2024-11-26 11:24:41.766 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.myskoda.climate.MySkodaClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/skodaconnect/homeassistant-myskoda/issues
2024-11-26 11:24:41.767 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.myskoda.climate.MySkodaClimate'>) does not set ClimateEntityFeature.TURN_ON …
```
> Fix climate feature error.

- custom_components/myskoda/climate.py
should be sufficient because Citigo iV doesnt have the other capability (AIR_CONDITIONING_SAVE_AND_ACTIVATE) but still can enable/disable AC from myskoda app
> AC changed to use only AIR_CONDITIONING capability 

- pyproject.toml
Disable packaging via poetry. 
We add the package as zip to the release for use with HACS instead.
> Disable packaging via poetry. 

- custom_components/myskoda/config_flow.py
By default MQTT is connected during the config flow when we check if your password is valid.
This is unneeded and causes many listeners for MQTT changes, making mqtt messages get processed multiple times.
Not only is this unneeded and clutters the logfiles, it also can cause more API calls than needed and slow down HA
Also, we keep this extra connection around, with no clear purpose. So let's clean it up.
> Disable MQTT connection during password check

- custom_components/myskoda/climate.py
From last few fixtures its seems like skoda changed `ACTIVE_VENTILATION` to `AUXILIARY_HEATING_BASIC`. Because of that ventilation was not available in AuxiliaryHeater entity. As I'm not sure if Skoda replaced that capability for all or only for some cars, I have modified the code to checks for both capabilities.
> show HVACMode.FAN_ONLY also for AUXILIARY_HEATING_BASIC

- custom_components/myskoda/sensor.py
Adds the OutsideTemperature (created in https://github.com/skodaconnect/homeassistant-myskoda/pull/388) as a HA sensor
> Fix OutsideTemperature sensor setup

- README.md
- custom_components/myskoda/diagnostics.py
fixtures can be downloaded directly using `DOWNLOAD DIAGNOSTICS` button from the device page. They will be returned in data object as this is the way how its implemented by HA. There are some other data but nothing private. Tried to return also yaml but no matter what I tried, formatting was always broken as its returned in dictionary. 
And probably we can remove `Generate Fixtures` button what do you think?
> add download diagnostics feature

- custom_components/myskoda/__init__.py
- custom_components/myskoda/coordinator.py
In a service disruption we have seen MQTT become unavailable.
Since we by default await the presence of the MQTT service, this blocks the integration from starting.
This PR changes behaviour in a subtle manner:
- The integration will initialise with only polling present
- As soon as regular updates are scheduled, we enable MQTT listening as well
> Prevent integration from stalling when MQTT does not connect

- custom_components/myskoda/coordinator.py
Hardcode a different update method for CitigoE as we learn how to cope with the limitations of this model.
This is expected to change over time, as we get more experience with this car model's behaviour. This model seems to dislike our polling of the vehicle health details very much, causing many errors in app and integration.
Fixes #212
> CitigoE iV partial update

- README.md
- custom_components/myskoda/button.py
Deprecate the fixtures button, since the functionality is in the Device Diagnostics now.
Schedule this for removal whenever we release v2.0.0
> Deprecate fixtures button

- custom_components/myskoda/coordinator.py
The refactoring is done according to #370 with minor modification. The flow is now following:
- if `vehicle.charging` is not available then it should be fetched
- if `vehicle.driving_range` is not available then it should be fetched
- the rest of the parsing is based on the fact which service event structure is in the event data. Currently there are only two options:
- `ServiceEventChargingData` that contains some data that can be stored to the vehicle status and driving range structures
- `ServiceEventData` that does not contain data. Since the event is received the status of the car has changed and it can be updated using `update_charging()` method
> Refactor _on_charging_event

- custom_components/myskoda/__init__.py
- custom_components/myskoda/translations/en.json
This adds integration handling for the new `MarketingConsentError` introduced in myskoda v0.15.4
> Handle marketing consent error in integration

- custom_components/myskoda/sensor.py
After disabling the `vehicle-health` endpoint for CitigoE in #431, the mileage sensor would become unpopulated, as reported in #458 and on Discord.
This introduces a fallback location for the mileage data.
> Introduce fallback for mileage sensor

- custom_components/myskoda/device_tracker.py
- custom_components/myskoda/image.py
With pr  #456 the main image render is replaced with exterior_front if unavailable.
Problem is that exterior_front is not available for all vehicles.
If exterior_front is unavailable now exterior_side is used
> fix for fix missing main render

- custom_components/myskoda/icons.json
- custom_components/myskoda/sensor.py
- custom_components/myskoda/translations/en.json
https://github.com/skodaconnect/homeassistant-myskoda/issues/238
> Add AdBlue range sensor

- README.md
> Doc: template sensor for vehicle_in_motion

- custom_components/myskoda/coordinator.py
CitigoE IV doesnt have auxiliary heater as that's available only for ICE and PHEV vehicles
> remove AuxiliaryHeating from partial update for CitigoE IV

- custom_components/myskoda/__init__.py
- custom_components/myskoda/button.py
- custom_components/myskoda/climate.py
- custom_components/myskoda/coordinator.py
- custom_components/myskoda/lock.py
- custom_components/myskoda/number.py
- custom_components/myskoda/switch.py
This renames references to ConfigEntry from `config` to `entry`:
- `config` is already used in relation to configurations of various climate entries
- The naming was inconsistent, sometimes `config`, sometimes `entry`
Found this while working on #447 and it annoyed me :grin:
> (chore) Reference ConfigEntry consistently

- custom_components/myskoda/sensor.py
Affected sensors: `AddBlueRange`, `CombustionRange`, `GasRange`, `GasLevel`, `Range`
After last update, they become unavailable because they are created only when some specific data from driving_range enpoint is present. This was changed as this data is not requested during initialization sequence
Those sensors will be created for vehicles based on the required or forbidden capabilities. Side effect is that some will be created also for vehicles which doesn't have this feature (for example AddBlueRange for all combustion vehicles). Because of that a `available()` property is used to make the sensor unavailable/available based on the data 
So for example users with combustion vehicles will see something like this:
Sensor is created, but set to unavailable. They can hide the sensor manually …
> workaround for unavailable sensors

- custom_components/myskoda/binary_sensor.py
missed this one in #517 - Sunroof sensors is created for all vehicles, and set unavailable for those without this feature
> fix sunroof sensor not being created

- custom_components/myskoda/coordinator.py
just a try to have a partial update during boot, and full update afterwards instead of reverting back in #524
For some reason full update is now triggered right after boot even its not called from the code
Also implemented check to prevent duplicate execution
@WebSpider - can you please test it on your place?
> fix boot sequence

- .github/workflows/lint.yaml
Same thing as skodaconnect/myskoda#319
> Fix CI by using snap install of Just

- custom_components/myskoda/entity.py
- custom_components/myskoda/number.py
- hacs.json
- poetry.lock
- pyproject.toml
This deals with security issues in jinja, which HA found reason to incorporate home-assistant/core/pull/133951
> Bump minimal homeassistant to from 2024.10 to 2025.1.0

- custom_components/myskoda/coordinator.py
There were couple of places inside `_on_charging_event()` where state was assigned without checking if its exists in the event data which caused sensor to go to `unknown` state in some cases as described in #608
> fix unknown states from _on_charging_event

- custom_components/myskoda/coordinator.py
This fixes a bug introduced by #614 causing updates to fail when user endpoint is cached
> Fix update failing when user endpoint cached

- custom_components/myskoda/button.py
- custom_components/myskoda/climate.py
- custom_components/myskoda/lock.py
- custom_components/myskoda/number.py
- custom_components/myskoda/switch.py
This adds a visual cue to HA users that the entity currently cannot be pressed:
When a write-action to MySkoda is happening, the entity is temporarily disabled.
When the write-action is done, or errored, the entity is re-enabled so it can be pressed again.
This also means that when a throttle is hit because the user is hitting a certain action too often, the absence of entity disable/enable becomes a visual cue that in fact nothing happened.
This is mostly a copy of what was done for the "Generate Fixtures" button, but i think it works nicely!
> Automatically enable/disable entity on write action

- custom_components/myskoda/coordinator.py
Previously, any charging update received via MQTT would result in an update of the `primary_engine` always.
For Hybrid vehicles this may result in incorrect sensor updates, since the primary engine can be a combustion engine.
This PR fixes this by only updating charging information if the engine is an electric one.
Fixes #655
> Update charging logic to only update when engine is electric

- poetry.lock
- pyproject.toml
voluptuous is already a dependency from HomeAssistant, we do not need to depend on it ourselves
> Remove voluptuous from dependencies

- custom_components/myskoda/climate.py
- custom_components/myskoda/config_flow.py
- custom_components/myskoda/coordinator.py
- custom_components/myskoda/entity.py
Always update `charging` and `driving_range` when we receive an event of type `EventCharging`.
The data contained in the charging event itself does not have all the related sensor information, causing charging releated sensors not to be updated at all when `EventCharging` is emitted more frequently than the polling interval.
Fixes #484
> Update all relevant sensors when receiving EventCharging

- custom_components/myskoda/sensor.py
As pointed out in #687 we sometimes do not show the service interval in km sensor.
Source of this turned out to be misconfigured dependencies on sensors.
The `Maintenance` object is always present, and does not have any requirements for mileage and inspection, looking at our fixtures. For oil inspection, it does depend on just the `FUEL_STATUS` capability.
This adjusts the sensors to meet those capabilities
> Fix dependencies for sensors

- custom_components/myskoda/sensor.py
In release v1.21.2 caching was added for the health endpoint to avoid 429 errors on this healthpoint for some car models. This sensor used this endpoint, which made the results being cached.
Swap this for the mileage report that we get from another endpoint, which seems to have a much higher tolerance for 429 errors for all models.
Fixes #693
> Swap source for mileage sensor, health endpoint is now cached

- README.md
- custom_components/myskoda/sensor.py
- custom_components/myskoda/translations/en.json
This introduces a sensor for vehicles that advertise having Air Conditioning:
`estimated_time_left_to_reach_target_temperature`
The value is calculated from the API `estimated_date_time_to_reach_target_temperature`, which indicates a point in time that is estimated when the AC reaches set time.
A time difference between now and that point in time is calculated. 
When that time difference is negative, the sensor will indicate 0, to make it clear there is no time left to reach target temperature.
Fixes #678
> Implement sensor indicating time left until AC has reached target

- custom_components/myskoda/coordinator.py
- custom_components/myskoda/manifest.json
- poetry.lock
- pyproject.toml
Let the MySkoda class handle updating the Vehicle upon processing charging events.
Now when receiving a charging event in the coordinator we just need to call set_updated_vehicle with the current (cached) Vehicle from MySkoda.
Fixes #731
Depends on https://github.com/skodaconnect/myskoda/pull/407 - test results in that PR as well.
> Delegate Vehicle updates from charging events

- custom_components/myskoda/switch.py
Related to #741
When turning a switch on or off would fail an errors with the details
was logged, followed by a success message.
Also includes minor refactor to de-duplicate some of the code, as well as
align these functions and their logging across all switches.
> Fix and refactor switch onoff logging

- custom_components/myskoda/manifest.json
- pyproject.toml
Drop version from pyproject.toml since it's not being used there (we don't package anything)
Planning to do a pre-release of this one first to confirm behavior after the large refactor.
> Bump version to 1.23.0

- custom_components/myskoda/sensor.py
Fixes #760
Hybrid CNG vehicles report `"car_type": "cng"`. Since I'm not sure if
_all_ those vehicles use that car_type I'm leaving in the `hybrid` car
type.
Also:
- Remove redundant capability condition in `available` method
- Avoid redeclaring `range` (builtin)
> fix: allow EngineType.CNG for Gas sensors

- custom_components/myskoda/sensor.py
Introduced in #767
Woops.
Can happen on startup.
```
2025-05-01T09:36:22.033377902Z   File "/config/custom_components/myskoda/sensor.py", line 548, in native_value
2025-05-01T09:36:22.033395550Z     last_value = int(last_state.state)
2025-05-01T09:36:22.033412235Z ValueError: invalid literal for int() with base 10: 'unavailable'
```
> fix: prevent value/type error when setting last mileage value

- custom_components/myskoda/coordinator.py
Fixes #765
Previously you'd have to wait for the next myskoda update or scheduled update to see events/operation updates in HA.
Now it's at the time of the operation/events, e.g.
```
2025-05-01T09:43:41.478567362Z 2025-05-01 09:43:41.458 DEBUG (MainThread) [myskoda.myskoda] Processing operation event: ...operation=<OperationName.UPDATE_CARE_MODE: 'update-care-mode'>, status=<OperationStatus.IN_PROGRESS: 'IN_PROGRESS'>, error_code=None, timestamp=None), type=<EventType.OPERATION: 'operation-request'>)
...
2025-05-01T09:44:41.289862310Z 2025-05-01 09:44:41.256 DEBUG (MainThread) [myskoda.myskoda] Processing operation event: ...operation=<OperationName.UPDATE_CARE_MODE: 'update-care-mode'>, status=<OperationStatus.COMPLETED_SUCCESS: 'COMPLETED_SUCCESS'>, error_code=None, timestamp=None), …
```
> fix: update HA after updating events/operations

- README.md
In TOC only show h2 and h3 since the only h1 is the title.
> doc: fix typo and TOC

- custom_components/myskoda/button.py
- custom_components/myskoda/icons.json
- custom_components/myskoda/translations/en.json
- docs/entities.md
Fixes: #762
Disabled by default to limit accidental use.
Adding service calls (actions) looked like it would actually be more work/complexity so I ended up going for a third option after the discussion in #762: directly add a new button, but keep it disabled by default. This means the use has to first intentionally find, update and enable the entity before being able to use it.
Seems to work ok on my Enyaq although I can't tell if it really does wake the car
```
2025-05-06T07:20:48.734252002Z 2025-05-06 07:20:48.729 DEBUG (MainThread) [myskoda.myskoda] Trace: POST https://mysmob.api.connect.skoda-auto.cz/api/v1/vehicle-wake - response: 202 (0 bytes)
```
I didn't see any MQTT event but I'm not seeing _any_ events right now so I think the MQTT broker might be down...
> feat: add button to wake up the car

- custom_components/myskoda/manifest.json
- pyproject.toml
- uv.lock
Bump myskoda to 1.2.0
- Fixes a missing errorType
- Adds support for the vehicle connection state
More details at https://github.com/skodaconnect/myskoda/releases/tag/v1.2.0
Fixes #781
> chore: bump myskoda to 1.2.0

- custom_components/myskoda/translations/en.json
This removes the state translations of binary sensors, since they are equal to the default translations inside HA.
Once the strings are removed from the reference language (English), our translation tool should provide us with an automatic PR to clean it up in all languages.
Thanks @ChristophCaina for pointing this out and providing the first fix, however as indicated in #576 he currently has other things to do.
Fixes #384
> chore(i10n): remove binary sensor state translations from localization

- README.md
Now that the integration is listed in HACS by default, users no longer need to add it as a custom repository. 
This commit updates the README to simplify the installation steps accordingly.
Fixes #784
> docs(readme): update installation instructions

- custom_components/myskoda/binary_sensor.py
- custom_components/myskoda/icons.json
Some refinements after collecting user feedback:
- Apparently the sensors are only available on Enyaq and Elroq cars. Collected fixtures teach us those are the only ones currently supporting the `READINESS` capability. Since the endpoint has the same name in it, it seems logical to gate the sensors behind this capability
- Add icons more suitable than the default ones from HA
A lot of thanks to all the beta users!
> fix: refinements for readiness sensors

- hacs.json
Downloading the zip is faster than checkout of the repo, and we create it in CI a while now.
> chore: instruct hacs to download the zip not checkout the repo

- custom_components/myskoda/manifest.json
- custom_components/myskoda/translations/en.json
- custom_components/myskoda/translations/nl.json
- custom_components/myskoda/translations/pt-BR.json
- custom_components/myskoda/translations/pt.json
Since the sensors are part of the release, they should not be named beta anymore.
Also bump the version to prepare for releasing just this fix.
> fix(i10n): remove beta from sensor names

- custom_components/myskoda/manifest.json
- pyproject.toml
- uv.lock
Changes:
- Support for deactivated capabilities (occurs on OTA update)
- Support for new marketing capability
- Update in TLS handling to prevent deprecation warnings
- Adds support for parking positions
- Documentation of app 8.4.0 endpoints
> chore: Bump myskoda to 2.3.2

- custom_components/myskoda/binary_sensor.py
Using "Running" from the available device classes seems more fitting than using "Problem".
Fixes #862
> fix: align sensor type of battery-protection with sensor values

- custom_components/myskoda/__init__.py
- custom_components/myskoda/binary_sensor.py
- custom_components/myskoda/config_flow.py
- custom_components/myskoda/translations/cs.json
- custom_components/myskoda/translations/da.json
- custom_components/myskoda/translations/de.json
- custom_components/myskoda/translations/en.json
- custom_components/myskoda/translations/fi.json
- custom_components/myskoda/translations/fr.json
- custom_components/myskoda/translations/hu.json
- custom_components/myskoda/translations/it.json
- custom_components/myskoda/translations/nl.json
- custom_components/myskoda/translations/no.json
- custom_components/myskoda/translations/pl.json
- custom_components/myskoda/translations/pt-BR.json
- custom_components/myskoda/translations/pt.json
- custom_components/myskoda/translations/ro.json
- custom_components/myskoda/translations/ru.json
- custom_components/myskoda/translations/sk.json
- custom_components/myskoda/translations/sl.json
- custom_components/myskoda/translations/sv.json
This PR changes the suffix in the unique_id of all LOCK type binary sensors from "locked" to "lock" to prevent confusion.
This still needs some testing to see if we migrate correctly.
Fixes #853
> fix: rename unique_id of binary sensor locks from 'locked' to 'lock'

- .github/dependabot.yml
Dependabot starts to clutter up the release notes. 
This ignores them by default, we can add them back in by manually removing the label.
> Ignore dependabot changes in release notes
